# Generated by Django 4.1.3 on 2022-12-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paseo_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('precio_costo', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Bien', 'Poco'), ('Mal', 'Mal'), ('Critico', 'Critico')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClienteTienda',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectivo')], max_length=15)),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True)),
                ('distrito', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=45)),
                ('nombre_dueño', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_alquiler', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('Juegos', 'Juegos'), ('Comida', 'Comida'), ('Ropa', 'Ropa')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=40, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('distrito', models.CharField(blank=True, max_length=30, null=True)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(blank=True, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
                ('nombres_cli', models.CharField(blank=True, max_length=30, null=True)),
                ('dni_cli', models.IntegerField(blank=True, null=True)),
                ('tipo_pago', models.CharField(choices=[('Targeta', 'Targeta'), ('Efectivo', 'Efectivo')], max_length=15)),
                ('numero_boleta', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('igb', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_tienda', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cli', models.ForeignKey(blank=True, db_column='id_cli', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paseo_central.registroclientetienda')),
                ('nombre_producto', models.ForeignKey(blank=True, db_column='nombre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paseo_central.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('administrador general', 'administrador general'), ('administrador nivel1', 'administrador nivel1'), ('administrador nivel2', 'administrador nivel2')], max_length=45)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paseo_central.usuarios')),
            ],
        ),
    ]
